# Generated by Django 5.2.8 on 2025-12-08 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_realizacao', models.DateField(verbose_name='Data de realização')),
                ('clinic_or_vet', models.CharField(max_length=255, verbose_name='Clínica / Veterinário')),
                ('exam_type', models.CharField(max_length=255, verbose_name='Exame')),
                ('pet_name', models.CharField(max_length=255, verbose_name='Pet')),
                ('breed', models.CharField(blank=True, max_length=255, verbose_name='Raça')),
                ('tutor_name', models.CharField(max_length=255, verbose_name='Tutor')),
                ('alerta_email', models.DateTimeField(blank=True, null=True, verbose_name='Alerta Email')),
                ('alerta_zap', models.DateTimeField(blank=True, null=True, verbose_name='Alerta Zap')),
                ('retorno_previsto', models.DateField(blank=True, null=True, verbose_name='Retorno previsto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_realizacao', '-created_at'],
            },
        ),
    ]
