# Generated by Django 5.2.8 on 2025-12-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='exam',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='exam_pdfs/', verbose_name='Arquivo PDF'),
        ),
        migrations.AddField(
            model_name='exam',
            name='tutor_email',
            field=models.CharField(blank=True, max_length=255, verbose_name='E-mail do tutor'),
        ),
        migrations.AddField(
            model_name='exam',
            name='tutor_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Celular do tutor'),
        ),
    ]
