# Generated by Django 5.2.8 on 2025-12-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_clinic_tutor_veterinarian_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('BASIC', 'Básico')], default='BASIC', max_length=10),
        ),
    ]
