# Generated by Django 5.2.8 on 2026-01-12 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_clinic_user_veterinarian_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='assigned_user',
            field=models.ForeignKey(blank=True, help_text='Conta (clínica/vet) que pode visualizar este exame', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_exams', to=settings.AUTH_USER_MODEL),
        ),
    ]
