# Generated by Django 5.2.8 on 2026-01-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_exam_assigned_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTypeAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=50, unique=True, verbose_name='Sigla')),
                ('full_name', models.CharField(max_length=255, verbose_name='Exame')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['abbreviation'],
            },
        ),
    ]
