# Generated by Django 5.2.8 on 2026-01-19 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_examtypealias'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamExtraPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='exam_pdfs/extras/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_pdfs', to='accounts.exam')),
            ],
        ),
    ]
