# Generated by Django 5.2.8 on 2026-01-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_examextrapdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={},
        ),
        migrations.AddField(
            model_name='tutor',
            name='identification',
            field=models.CharField(blank=True, max_length=255, verbose_name='Identificação'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='surname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
