# Generated by Django 5.2.8 on 2026-02-08 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_tutor_options_clinic_complement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='complement',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='identification',
        ),
        migrations.RemoveField(
            model_name='veterinarian',
            name='complement',
        ),
    ]
