# Generated by Django 5.2.8 on 2026-02-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_clinic_complement_remove_tutor_identification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='additional_clinic_or_vet',
            field=models.JSONField(blank=True, default=list, verbose_name='Clínicas/Vets adicionais'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('BASIC', 'Básico'), ('TUTOR', 'Tutor')], default='BASIC', max_length=10),
        ),
    ]
