# Generated by Django 5.2.8 on 2026-02-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_exam_additional_clinic_or_vet_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('ADMIN_AUX', 'Administrador Auxiliar'), ('BASIC', 'Básico'), ('TUTOR', 'Tutor')], default='BASIC', max_length=10),
        ),
    ]
