# Generated by Django 5.2.8 on 2026-03-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='management_photos/clinicas/'),
        ),
        migrations.AddField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='management_photos/pets/'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='management_photos/tutores/'),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='management_photos/veterinarios/'),
        ),
    ]
