# Generated by Django 5.2.8 on 2026-03-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_clinic_photo_pet_photo_tutor_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='retorno_horario',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário do retorno'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='retorno_previsto',
            field=models.DateField(blank=True, null=True, verbose_name='Retorno'),
        ),
    ]
