# Generated by Django 5.2.8 on 2026-03-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_exam_retorno_horario_alter_exam_retorno_previsto'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='alerta_provider',
            field=models.BooleanField(default=False),
        ),
    ]
