# Generated by Django 5.2.8 on 2026-03-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_exam_alerta_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='retorno_alert_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='retorno_alert_processed_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
