# Generated by Django 5.2.8 on 2026-04-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_exam_retorno_alert_processed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='exams_per_page',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='management_per_page',
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
